# Generated by Django 3.0.3 on 2020-05-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='message',
            field=models.CharField(default='тестовое сообщение', max_length=100),
            preserve_default=False,
        ),
    ]
