# Generated by Django 3.0.3 on 2020-05-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prox', '0002_address_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
